import { Command } from '../commandRegistry';
import {
  LayoutDashboard,
  CheckSquare,
  Calendar,
  Mail,
  FileText,
  Settings,
  Sparkles,
  MessageSquare,
  Link2,
} from 'lucide-react';

export const navigationCommands: Command[] = [
  {
    id: 'nav-dashboard',
    title: 'Go to Dashboard',
    description: 'View your daily overview',
    icon: LayoutDashboard,
    keywords: ['dashboard', 'home', 'today', 'overview'],
    aliases: ['home', 'main', 'today'],
    tags: ['navigation', 'quick'],
    category: 'navigation',
    shortcut: 'G → D',
    availability: ['global'],
    href: '/dashboard',
    action: () => {},
  },
  {
    id: 'nav-tasks',
    title: 'Go to Tasks',
    description: 'Manage your tasks',
    icon: CheckSquare,
    keywords: ['tasks', 'todo', 'kanban', 'work'],
    aliases: ['todos', 'task list', 'kanban board'],
    tags: ['navigation', 'productivity'],
    category: 'navigation',
    shortcut: 'G → T',
    availability: ['global'],
    href: '/dashboard/tasks',
    action: () => {},
  },
  {
    id: 'nav-calendar',
    title: 'Go to Calendar',
    description: 'View your schedule',
    icon: Calendar,
    keywords: ['calendar', 'events', 'meetings', 'schedule'],
    category: 'navigation',
    shortcut: 'G → C',
    availability: ['global'],
    href: '/dashboard/calendar',
    action: () => {},
  },
  {
    id: 'nav-gmail',
    title: 'Go to Messages',
    description: 'Check your Gmail',
    icon: Mail,
    keywords: ['gmail', 'messages', 'email', 'inbox'],
    aliases: ['mail', 'inbox', 'email'],
    tags: ['navigation', 'communication'],
    category: 'navigation',
    shortcut: 'G → M',
    availability: ['global'],
    href: '/dashboard/gmail',
    action: () => {},
  },
  {
    id: 'nav-documents',
    title: 'Go to Documents',
    description: 'Browse your documents',
    icon: FileText,
    keywords: ['documents', 'files', 'notion', 'notes'],
    category: 'navigation',
    shortcut: 'G → D',
    availability: ['global'],
    href: '/dashboard/documents',
    action: () => {},
  },
  {
    id: 'nav-ai-assistant',
    title: 'Go to AI Assistant',
    description: 'Chat with AURA AI',
    icon: MessageSquare,
    keywords: ['ai', 'assistant', 'chat', 'help'],
    category: 'navigation',
    shortcut: 'G → A',
    availability: ['global'],
    href: '/dashboard/ai-assistant',
    action: () => {},
  },
  {
    id: 'nav-ai-digest',
    title: 'Go to AI Digest',
    description: 'View your daily AI digest',
    icon: Sparkles,
    keywords: ['digest', 'summary', 'ai', 'daily'],
    category: 'navigation',
    shortcut: 'G → I',
    availability: ['global'],
    href: '/dashboard/ai-digest',
    action: () => {},
  },
  {
    id: 'nav-integrations',
    title: 'Go to Integrations',
    description: 'Manage your connections',
    icon: Link2,
    keywords: ['integrations', 'connections', 'oauth', 'google', 'notion'],
    category: 'navigation',
    shortcut: 'G → N',
    availability: ['global'],
    href: '/dashboard/integrations',
    action: () => {},
  },
  {
    id: 'nav-settings',
    title: 'Go to Settings',
    description: 'Configure your preferences',
    icon: Settings,
    keywords: ['settings', 'preferences', 'profile', 'account'],
    category: 'navigation',
    shortcut: 'G → S',
    availability: ['global'],
    href: '/dashboard/settings',
    action: () => {},
  },
];
